<?php
// $Id$
/**
 * @file summify.module
 * Summify module
 */

define('SUMMIFY_HOME', 'http://summify.com');

/**
 * Implementation of hook_help().
 */
function summify_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/summify':
      $output = '<p>'. t("In order to enable Summify for your Drupal website you need to specify your Summify username. (<a href=\"" . SUMMIFY_HOME . "/register/\">Register here</a> if you haven't already.)") .'</p>';
      $output .= '<p>'. t("Once you specify your Summify username you can tweak and configure the Summify widget by visiting the <a href=\"" . SUMMIFY_HOME. "/dashboard/\">Summify dashboard</a>.") .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function summify_menu() { 
  $items['admin/settings/summify'] = array(
    'title' => 'Summify',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('summify_manage_settings'),
    'access arguments' => array('administer summify'),
   );
  return $items;
}

function summify_manage_settings() {
  $form = array();
  $form['summify_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Summify username'),
    '#description' => t('Please enter your Summify username.'),
    '#default_value' => variable_get('summify_username', ''),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Test & Save Configuration'),
  );
  return $form; 
}
 
function summify_manage_settings_validate($form, &$form_state) {
  $username = $form_state['clicked_button']['#post']['summify_username'];
  if (trim($username) == '') {
    form_set_error('summify_username', t('Please enter your Summify username.'));
    return;
  }
  $client_id = summify_get_default_client_id($username);
  if (!$client_id) {
    form_set_error('summify_username', SUMMIFY_HOME . ' ' .t('does not recognize this username.'));
  }
}

function summify_manage_settings_submit($form, &$form_state) {
  $username = $form_state['clicked_button']['#post']['summify_username'];
  $client_id = summify_get_default_client_id($username);
  variable_set('summify_username', $username);
  variable_set('summify_client_id', $client_id);
  drupal_set_message(t('The Summify options have been saved. Your client ID is ') . $client_id);
}

/**
 * Call the Summify endpoint to obtain the default client_id for given
 * username.
 *
 * Return client_id or FALSE if not found.
 */
function summify_get_default_client_id($username) {
  $curl = curl_init(); 
  $request_url = SUMMIFY_HOME . "/user-api/default_client_id/" . urlencode($username);
  curl_setopt($curl, CURLOPT_URL, $request_url);
  // Return the transfer as a string 
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
  $response = curl_exec($curl);
  $response_info = curl_getinfo($curl);
  curl_close($curl);
  if ($response_info['http_code'] != 200) {
    return FALSE;
  } else {
    return $response;
  }
}

/**
 * Implementation of hook_perm().
 */
function summify_perm() {
  return array('administer summify');
}

/**
 * Implementation of hook_footer().
 */
function summify_footer($main = 0) {
  $username = variable_get('summify_username', '');
  $client_id = variable_get('summify_client_id', '');
  if ($username && $client_id) {
    $script_src = SUMMIFY_HOME . "/client/v1/" . urlencode($client_id) . "/client.js";
    $script_tag = "<script text=\"text/javascript\" src=\"". htmlentities($script_src) . "\"></script>\n";
    return $script_tag;
  }
  return '';
}
