<?php
// $Id$
/**
 * @file summify.module
 * Summify module
 */

/**
 * Implementation of hook_menu().
 */
function summify_menu() { 
  $items['admin/settings/summify'] = array(
    'title' => 'Summify',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('summify_manage_settings'),
    'access arguments' => array('administer summify'),
   );
  return $items;
}

function summify_manage_settings() {
  $form['summify_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Summify username'),
    '#description' => 'Please enter your Summify username. You can sign up for an username at http://summify.com/',
    '#value' => variable_get('summify_username', ''),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Test & Save Configuration'),
  );
  return $form; 
}
 
function summify_manage_settings_submit($form, &$form_state) {
  variable_set('summify_username', $form_state['clicked_button']['#post']['summify_username']);
  drupal_set_message('The Summify options have been saved.');  
}

/**
 * Implementation of hook_perm().
 */
function summify_perm() {
  return array('administer summify');
}

/**
 * Implementation of hook_footer().
 */
function summify_footer($main = 0) {
  $summify_username = variable_get('summify_username', '');
  if ($summify_username != '') {
    $client_id = '2100ad';
    $script_src = "http://summify.com/client/v1/{$client_id}/client.js";
    $script_tag = "<script text=\"text/javascript\" src=\"{$script_src}\"></script>\n";
    return $script_tag;
  }
  return '';
}
